'use strict';
const typeName = {
    "force": "内功",
    "dodge": "轻功",
    "parry": "招架",
    "unarmed": "拳脚",
    "weapon": "武器",
};

class 武道 {
    constructor(name, prop, value, unit, type, id) {
        this.name = name; // 名字
        this.prop = prop; // 属性变化
        this.value = value; // 属性数值 number
        this.type = type;
        this.unit = unit; // 属性单位
        this.id = id; // 
    }
    getText(lv, level) {
        return `${typeName[this.type]}【${this.name}】${this.prop}${Math.floor(this.value*lv*level/5000)}`;
    }
};
const 武道清单 = [
    // 内功
    new 武道("御气之道", "内力上限＋", 125000, "", "force", 0),
    new 武道("防御之道", "防御＋", 2500, "", "force", 1),
    new 武道("气血之道", "气血＋", 60000, "", "force", 2),
    new 武道("炼体之术", "根骨＋", 400, "", "force", 3),
    new 武道("强体之术", "臂力＋", 300, "", "force", 4),
    new 武道("永生之道", "年龄－", 10, "岁", "force", 5),
    new 武道("守护之心", "免伤＋", 5, "%", "force", 6),
    new 武道("暴虐之道", "终伤＋", 5, "%", "force", 7),
    // 轻功
    new 武道("躲闪之道", "躲闪＋", 2500, "", "dodge", 8),
    new 武道("防御之道", "防御＋", 2500, "", "dodge", 9),
    new 武道("御气之道", "内力上限＋", 110000, "", "dodge", 10),
    new 武道("命中之道", "命中＋", 2000, "", "dodge", 11),
    new 武道("轻盈之道", "身法＋", 300, "", "dodge", 12),
    // 招架
    new 武道("招架之道", "招架＋", 2400, "", "parry", 13),
    new 武道("气血之道", "气血＋", 47500, "", "parry", 14),
    new 武道("御气之道", "内力上限＋", 110000, "", "parry", 15),
    new 武道("防御之道", "防御＋", 2000, "", "parry", 16),
    new 武道("明悟之术", "悟性＋", 150, "", "parry", 17),
    new 武道("炼体之术", "根骨＋", 300, "", "parry", 18),
    // 拳脚
    new 武道("命中之道", "命中＋", 2500, "", "unarmed", 19),
    new 武道("进攻之道", "攻击＋", 2150, "", "unarmed", 20),
    new 武道("御气之道", "内力上限＋", 110000, "", "unarmed", 21),
    new 武道("防守之道", "防御＋", 2000, "", "unarmed", 22),
    new 武道("招架之道", "招架＋", 2000, "", "unarmed", 23),
    new 武道("强体之术", "臂力＋", 400, "", "unarmed", 24),
    // 武器
    new 武道("精准之道", "命中＋", 2300, "", "weapon", 25),
    new 武道("防守之道", "防御＋", 2300, "", "weapon", 26),
    new 武道("进攻之道", "攻击＋", 2000, "", "weapon", 27),
    new 武道("招架之道", "招架＋", 2000, "", "weapon", 28),
    new 武道("强体之术", "臂力＋", 300, "", "weapon", 29),
    new 武道("躲闪之道", "躲闪＋", 2000, "", "weapon", 30),
    new 武道("残暴之心", "暴击＋", 2.5, "%", "weapon", 31),
];
const 技能清单={
// 武当派
                 "wudangxinfa": 1,
                 "wudangjianfa": 1,
                 "wudangchangquan": 1,
                 "tiyunzong": 2,
                 "taijishengong": 3,
                 "taijiquan": 3,
                 "taijijian": 4,
                 "taijiquan2": 4,
                 "tiyunzong2": 4,
                 "taijijian2": 5,
                 "taijishengong2": 5,
                // 少林派
                "shaolinshenfa": 1,
                "ranmudao": 3,
                "yizhichan": 3,
                "yijinjing": 4,
                "weituogun": 1,
                "hunyuanyiqi": 1,
                "fuhuquan": 1,
                "damojian": 2,
                "jingangquan": 2,
                "shaolinshenfa2": 4,
                "yizhichan2": 4,
                "ranmudao2": 5,
                "yijinjing2": 5,
                // 华山派
                "poyuquan": 1,
                "zixiashengong": 3,
                "kuangfengkuaijian": 3,
                "dugujiujian": 4,
                "feiyanhuixiang": 1,
                "huashanxinfa": 1,
                "huashanjianfa": 1,
                "huashanquanfa": 1,
                "poyuquan2": 4,
                "zixiashengong2": 4,
                "dugujiujian2": 5,
                "kuangfengkuaijian2": 5,
                // 峨眉派
                "zhutianbu": 1,
                "linjizhuang": 3,
                "jiuyinbaiguzhao": 3,
                "yitianjianfa": 4,
                "emeixinfa":1,
                "jindingzhang": 1,
                "huifengjian": 2,
                "jiuyinbaiguzhao2": 4,
                "zhutianbu2": 4,
                "linjizhuang2": 5,
                "yitianjianfa2": 5,
                // 逍遥派
                 "lingboweibu": 3,
                 "beimingshengong": 3,
                 "liuyangzhang": 3,
                 "xiaowuxianggong": 4,
                 "ruyidao": 1,
                 "xiaoyaoxinfa": 1,
                 "zhemeishou": 2,
                 "beimingshengong2": 4,
                 "liuyangzhang2": 4,
                 "lingboweibu2": 5,
                 "xiaowuxianggong2": 5,
                // 丐帮
                 "huntianqigong2": 4,
                 "xiaoyaoyou2": 4,
                 "dagoubang2": 5,
                 "xianglongzhang2": 5,
                 "xiaoyaoyou": 2,
                 "dagoubang": 3,
                 "huntianqigong": 3,
                 "xianglongzhang": 4,
                 "jiaohuabangfa": 1,
                 "feiyanzoubi": 1,
                 "gaibangxinfa": 1,
                 "taizuchangquan": 1,
                // 杀手楼
                 "shashoubufa": 1,
                 "shashouxinfa": 1,
                 "chuanxinzhang": 2,
                 "shashengjue": 3,
                 "taxuexunmei": 3,
                 "mantianhuayu": 4,
                 "feidao": 1,
                 "chuanxinzhang2": 4,
                 "shashengjue2": 4,
                 "mantianhuayu2": 5,
                 "taxuexunmei2": 5,
                // 公共内功
                 "hamagong": 4,
                 "huagongdafa": 4,
                 "mingyugong": 4,
                 "kumushengong": 4,
                 "shenzhaojing": 4,
                 "xuehaimogong": 4,
                 "longxianggong": 5,
                 "kuihuashengong": 5,
                 "bahuanggong": 5,
                 "jiuyangshengong": 5,
                 "jiuyinshengong": 5,
                 "taixuangong": 5,
                 "mizongxinfa": 1,
                 "yunlongxinfa": 1,
                 "lengyueshengong": 1,
                 "shenlongxinfa": 2,
                 "wudushengong": 2,
                 "biboshengong": 2,
                 "baiyunxinfa": 3,
                 "zhenyuejue": 3,
                 "shenghuoshengong": 3,
                 "hanbingzhenqi": 4,
                 "xiantiangong": 4,
                 "mengguxinfa": 2,
                 "panshishengong": 3,
                 "yunvxinjing": 3,
                // 公共轻功
                 "shenxingbaibian": 2,
                 "tagexing": 2,
                 "tiannanbu": 2,
                 "jinsheyoushenbu": 3,
                 "wuduyanluobu": 3,
                 "anyingfuxiang": 3,
                 "xuanxubu": 4,
                 "yixingbufa": 1,
                 "yunlongshenfa": 1,
                 "jinyangong": 1,
                 "sixiangbu": 2,
                 "hengshanshenfa": 2,
                 "chuanyunzong": 2,
                 "chanchubufa": 2,
                 "qingfushenfa": 2,
                 "zhaixingong": 2,
                 "shenkongxing": 2,
                // 公共拳脚
                 "yingzhuagong": 2,
                 "jinshezhang": 3,
                 "dasongyangshenzhang": 3,
                 "qishangquan": 3,
                 "sanyinzhua": 3,
                 "tanzhishengong": 4,
                 "kongmingquan": 4,
                 "canhezhi": 4,
                 "liumaishenjian": 5,
                 "anranxiaohun": 5,
                 "taizuchangquan": 1,
                 "dashouyin": 1,
                 "houquan": 1,
                 "huagumianzhang": 2,
                 "baguaquan": 2,
                 "liuyunzhang": 2,
                 "taishanquanfa": 2,
                 "jueqingzhang": 2,
                 "tianchangzhang": 3,
                 "cuixinzhang": 3,
                 "yiyangzhi": 4,
                // 公共招架
                "yihuajiemu": 4,
                "douzhuanxingyi": 5,
                "qiankundanuoyi": 5,
                // 公共剑法
                 "hengshanwushenjian": 3,
                 "quanzhenjianfa": 3,
                 "bixiejianfa": 5,
                 "xuantiejianfa": 5,
                 "shenlongjian": 1,
                 "tangshijianfa": 1,
                 "yunlongjian": 2,
                 "shenghuojianfa": 2,
                 "jinshejianfa": 3,
                 "wudugoufa": 3,
                 "hengshanjianfa": 3,
                 "songfengjianfa": 3,
                 "songshanjianfa": 3,
                 "luoyingshenjian": 3,
                 "yifengjian": 3,
                 "tianyuqijian": 3,
                 "shenjianjue": 2,
                 "taishanjianfa": 3,
                 "duanjiajianfa": 3,
                // 公共刀法
                "wuhuduanmendao": 1,
                "hujiadaofa": 2,
                "kuangfengkuaidao": 3,
                "xuedao": 5,
                // 公共棍法
                "juemengun": 1,
                "baguagun": 2,
                "zhongpingqiang": 3,
                "mengguqiangfa": 3,
                // 公共杖法
                 "shedaoqigong": 2,
                 "lingshezhangfa": 4,
                 "wuchangzhang": 2,
                // 公共鞭法
                 "yunlongbian": 1,
                 "qiufengfuchen": 1,
                 "yinsuojinling": 3,
                // 公共暗器
                 "jinshezhui": 2,
                 "feixingshu": 2,
                // 补充  "": 6,
                 "wunianchangong": 5,
                 "rulaishenzhang": 5,

                 "changshengjue": 6,
                 "cihangjiandian": 6,
                 "yinyangjiuzhuan": 6,
};